#!/bin/bash
# ---- Changelog ----
# [2026-03-11] Claude (Opus 4.6) — Initial implementation.
#   What: PreToolUse hook that injects context reminders when CC reads
#         large, critical files (neuro_foundation.py, openclaw_hook.py).
#   Why:  CC must not edit these files based on grep results alone.
#         3,661 lines of SNN engine has deep interdependencies.
#         858 lines of singleton wiring has the Grok contamination precedent.
#   How:  Checks file_path against critical files. Exit 0 with
#         additionalContext JSON — does not block, just injects wisdom.
# -------------------
#
# HOOK: PreToolUse
# MATCHER: Read|View
# PURPOSE: Inject context reminder when reading critical files.
# EXIT 0: Always allows the read. Adds additionalContext if critical file.

set -uo pipefail

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | jq -r '
    .tool_input.file_path //
    .tool_input.path //
    .tool_input.file //
    empty
' 2>/dev/null)

if [ -z "$FILE_PATH" ]; then
    exit 0
fi

NG_DIR="$HOME/NeuroGraph"

if [[ ! "$FILE_PATH" = /* ]]; then
    if [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then
        FILE_PATH="$CLAUDE_PROJECT_DIR/$FILE_PATH"
    else
        FILE_PATH="$NG_DIR/$FILE_PATH"
    fi
fi

FILE_PATH=$(realpath -m "$FILE_PATH" 2>/dev/null || echo "$FILE_PATH")
BASENAME=$(basename "$FILE_PATH")

# ── neuro_foundation.py ───────────────────────────────────────────
if [ "$BASENAME" = "neuro_foundation.py" ] && [[ "$FILE_PATH" == "$NG_DIR"* ]]; then
    cat <<EOF
{
  "additionalContext": "CONTEXT-FIRST REMINDER: neuro_foundation.py is 3,661 lines. This is Syl's SNN engine. STDP interacts with eligibility traces which interact with reward injection which interact with prediction bonuses. Changing one without understanding the others will cause subtle damage that may not surface for hundreds of timesteps. Read at least 100 lines of surrounding context before considering ANY edit. Do NOT edit this file based on grep results. This file is PROTECTED — requires Josh approval and backup confirmation before any modification."
}
EOF
    exit 0
fi

# ── openclaw_hook.py ──────────────────────────────────────────────
if [ "$BASENAME" = "openclaw_hook.py" ] && [[ "$FILE_PATH" == "$NG_DIR"* ]]; then
    cat <<EOF
{
  "additionalContext": "CONTEXT-FIRST REMINDER: openclaw_hook.py is 858 lines. This is the singleton that makes Syl whole — ingestion, SNN step, CES init, auto-save. HISTORICAL FAILURE: The Grok contamination incident appended module-level code outside the class, creating competing definitions. ALL code must live inside NeuroGraphMemory class or documented helper functions. This file is PROTECTED — requires Josh approval and backup confirmation before any modification."
}
EOF
    exit 0
fi

# ── ng_lite.py (vendored canonical) ───────────────────────────────
if [ "$BASENAME" = "ng_lite.py" ] && [[ "$FILE_PATH" == "$NG_DIR"* ]]; then
    cat <<EOF
{
  "additionalContext": "VENDORED FILE REMINDER: This is the CANONICAL source of ng_lite.py. Every module in the ecosystem vendors a copy from here. Any change to this file must be intentional for ALL modules, not just NeuroGraph. After editing, re-vendor to TID, TrollGuard, and all other modules. Requires Josh approval."
}
EOF
    exit 0
fi

# Not a critical file — no additional context needed
exit 0
